### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by dewelinski** [postyou/contao-background-image#1]
I set a background-image in a Content-Element (ce_text). After refreshing the Page i get an Fatal Error. 
It seems that the problem is caused in the BackgroundImageModel.php on line 27

**Error Message:**
Fatal error: Uncaught exception Exception with message Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'method="get" enctype="application/x-www-form-urlencoded" class="form-inline(\")"' at line 1 (SELECT id,addBackgroundImage,backgroundImageFilepath,backgroundImagePos FROM tl_article WHERE alias='f2\" method=\"get\" enctype=\"application/x-www-form-urlencoded\" class=\"form-inline' OR cssID REGEXP "(a:2:{i:0;s:)[0-9]+(:\")f2" method="get" enctype="application/x-www-form-urlencoded" class="form-inline(\")") thrown in system\modules\core\library\Contao\Database\Statement.php on line 295
#0 system\modules\core\library\Contao\Database\Statement.php(264): Contao\Database\Statement->query()
#1 system\modules\background-image\classes\BackgroundImageModel.php(27): Contao\Database\Statement->execute('f2" method="get...')
#2 system\modules\core\classes\FrontendTemplate.php(54): postyou\BackgroundImageModel->parseFrontendTemplateHook('\n\n
parse()
#4 system\modules\core\modules\ModuleArticle.php(67): Contao\Module->generate()
#5 system\modules\core\library\Contao\Controller.php(417): Contao\ModuleArticle->generate(true)
#6 composer\vendor\contao-bootstrap\modal\src\Netzmacht\Bootstrap\Modal\ModalModule.php(145): Contao\Controller::getArticle('765', false, true)
#7 composer\vendor\contao-bootstrap\modal\src\Netzmacht\Bootstrap\Modal\ModalModule.php(91): Netzmacht\Bootstrap\Modal\ModalModule->getContent()
#8 system\modules\core\modules\Module.php(287): Netzmacht\Bootstrap\Modal\ModalModule->compile()
#9 composer\vendor\contao-bootstrap\modal\src\Netzmacht\Bootstrap\Modal\ModalModule.php(119): Contao\Module->generate()
#10 system\modules\core\library\Contao\Controller.php(321): Netzmacht\Bootstrap\Modal\ModalModule->generate()
#11 system\modules\core\pages\PageRegular.php(137): Contao\Controller::getFrontendModule(Object(Contao\ModuleModel), 'modal-section')
#12 system\modules\core\controllers\FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#13 index.php(20): Contao\FrontendIndex->run()
#14 {main}

**Comment by dewelinski** [comment]
I fixed the Problem. The problem was an syntax error in `$alias[0]`

I add this code after line 25 in the BackgroundImageModel.php

`if(preg_match("/\"/",$alias[0])){
$alias_0 = str_replace('"','\"',$alias[0]);
}else{
$alias_0 = $alias[0];
}`

And i change the variable `$alias[0]` to `$alias_0`

**Comment by garyee** [comment]
I would say that it is not a good idea to use a hook like this, but I did not find a better solution. Thank you for reporting and bringing a solution! https://github.com/postyou/contao-background-image/commit/83f9954670c046634645fdb43861c11c3fbc3fbf

**Comment by garyee** [comment]
Just saw that you forked a little bit to late, next time feel free to PR ;)
